---
env:
  - ROLE_NAME=stone-payments.mongodb
sudo: required
services:
  - docker
language: python
python:
    - "3.7"
before_install:
  - deactivate
  - sudo pip install docker-py
  - source ~/virtualenv/python3.7/bin/activate
  - ln -s $TRAVIS_BUILD_DIR $(dirname "$TRAVIS_BUILD_DIR")/$ROLE_NAME
  - pip install molecule ansible
  - molecule dependency
script:
  - molecule converge -s default
  - molecule converge -s replica-set
