- name: install pymongo
  pip:
    name: pymongo
    state: latest
  when:  mongodb_pip_index_url == ""
    
- name: install pymongo from custom index
  pip:
    name: pymongo
    state: latest
    extra_args: -i "{{ mongodb_pip_index_url }}"
  when:  mongodb_pip_index_url|default("") != "" 
  
- name: remove old broken sysV script
  file:
    path: "/etc/rc.d/init.d/mongod"
    state: absent
  notify: reload systemd

- name: configure mongodb group
  group:
    name: "{{ mongodb_daemon_user }}"
    state: present

- name: configure mongodb user
  user:
    name: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    shell: /bin/false
    state: present

- name: create mongodb-writable directories
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    mode: "0755"
  with_items:
    - path: "{{ mongodb_conf_dbPath }}"
    - path: "{{ mongodb_conf_pidFile | dirname }}"
  notify: mongodb restart

- name: create mongodb read-only directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - path: "{{ mongodb_conf_file | dirname }}"
    - path: "{{ mongodb_replSet_keyFile | dirname }}"
  notify: mongodb restart
