---
- name: ensure mongo from EPEL is not installed
  yum:
    name:
      - mongodb
      - mongodb-server
      - python-pymongo
    state: absent

- name: ensure no leftover unit files from previous installations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/mongodb.service
    - /etc/systemd/system/mongodb-server.service
    - /etc/systemd/system/mongodb-org.service
    - /etc/systemd/system/mongodb-org-server.service
  notify: systemd reload

- meta: flush_handlers

- name: install MongoDB {{ mongodb_install_major }}.{{ mongodb_install_minor }} RPM GPG key
  rpm_key:
    state: present
    key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_install_major }}.{{ mongodb_install_minor }}.asc"

- name: install MongoDB {{ mongodb_install_major }}.{{ mongodb_install_minor }} repo
  yum_repository:
    name: mongodb
    description: "MongoDB Repo"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_install_major }}.{{ mongodb_install_minor }}/$basearch/"
    gpgcheck: true
    state: present

- name: install MongoDB package
  yum: name={{item}} state=present
  with_items:
    - mongodb-org-{{mongodb_install_major}}.{{mongodb_install_minor}}.{{mongodb_install_patch}}
    - mongodb-org-server-{{mongodb_install_major}}.{{mongodb_install_minor}}.{{mongodb_install_patch}}
    - numactl
    - python-pip

- name: install pymongo
  pip:
    name: pymongo
    state: latest

- name: remove old broken sysV script
  file:
    path: "/etc/rc.d/init.d/mongod"
    state: absent
  notify: reload systemd

- name: configure SELinux for MongoDB
  include: selinux.yml
  when: mongodb_install_selinux
